# [START app_yaml]
runtime: nodejs
vm: true
skip_files:
  - ^(.*/)?.*/node_modules/.*$
threadsafe: true
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: .7
resources:
  cpu: .2
  memory_gb: .15

# [START env_variables]
env_variables:
    NODE_ENV: production
    BASE_URL: 'http://timeclock.kandj.org'
    GCLOUD_PROJECT: 'timeclock-1355'
    GOOGLE_CLIENT_ID: '297000402789-nubthf0guot6kfa1696qq7i82mi5494g.apps.googleusercontent.com'
    GOOGLE_CLIENT_SECRET: 'LQqYLbHbCDN-sxuyqYzRz3_J'
# [END env_variables]

# [END app_yaml]
